import Head from "next/head";
import Header from "../components/Header";
import Body from "../components/Body";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Abhishek - Develop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Body />
    </div>
  );
}
