import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-black">
        <h2 className="text-white font-extrabold text-slate-400">Hi</h2>
      </div>
    </div>
  );
}
